{
 "title": "Eleveo dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Python bottle web",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"app-bottle.service\"}"
    }
   ]
  },
  {
   "title": "Boot time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_boot_time_seconds" }
   ]
  },
  {
   "title": "Memory free bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "httpd requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total"
    }
   ]
  }
 ]
}